name: retask
description: "A modern task management app with customizable themes, step tracking, and smart notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.0.3
  
  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Date and Time
  intl: ^0.20.0
  timezone: ^0.10.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8
  
  # Code Quality
  flutter_lints: ^3.0.1  # Fixed invalid version

# Flutter Configuration
flutter:
  uses-material-design: true
  
  # Add any assets, fonts, or other resources here
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
